azs:
- cloud_properties:
    availability_zone: us-west-2a
  name: z1
compilation:
  az: z1
  network: default
  reuse_compilation_vms: true
  vm_type: large
  workers: 5
disk_types:
- cloud_properties:
    encrypted: true
    type: gp3
  disk_size: 2048
  name: default
- cloud_properties:
    encrypted: true
    type: gp3
  disk_size: 2048
  name: consul
- cloud_properties:
    encrypted: true
    type: gp3
  disk_size: 10240
  name: concourse
- cloud_properties:
    encrypted: true
    type: gp3
  disk_size: 4096
  name: postgres
- cloud_properties:
    encrypted: true
    type: gp3
  disk_size: 4096
  name: blobstore
- cloud_properties:
    encrypted: true
    type: gp3
  disk_size: 1024
  name: vault
- cloud_properties:
    encrypted: true
    type: gp3
  disk_size: 65536
  name: bosh
- cloud_properties:
    encrypted: true
    type: gp3
  disk_size: 131072
  name: bosh-large
- cloud_properties:
    encrypted: true
    type: gp3
  disk_size: 2048
  name: shield
- cloud_properties:
    encrypted: true
    type: gp3
  disk_size: 51200
  name: prometheus
- cloud_properties:
    encrypted: true
    type: gp3
  disk_size: 4096
  name: rabbitmq
- cloud_properties:
    encrypted: true
    type: gp3
  disk_size: 5120
  name: 5GB
- cloud_properties:
    encrypted: true
    type: gp3
  disk_size: 10240
  name: 10GB
- cloud_properties:
    encrypted: true
    type: gp3
  disk_size: 100240
  name: 100GB
- cloud_properties:
    encrypted: true
    type: gp3
  disk_size: 10240
  name: minio
exodus:
  atc_ca_cert: REDACTED
  bosh: baby-bosh
  dated: 2022-08-10 13:29:26 +0000
  deployer: ubuntu
  external_url: https://10.4.68.6
  features: small-footprint,self-signed-cert
  is_director: false
  kit_is_dev: true
  kit_name: concourse
  kit_version: 4.1.3-rc.5
  mode: small-footprint
  password: REDACTED
  self-signed: true
  tsa_host: 10.4.68.6
  tsa_host_public_key: REDACTED
  tsa_port: 2222
  tsa_worker_private_key: REDACTED
  tsa_worker_public_key: REDACTED
  use_create_env: false
  username: concourse
  vault_base: /secret/baby/bosh/concourse
  version: 2.8.5
genesis:
  ci_mount: /secret/ci/
  env: baby-bosh
  exodus_mount: /secret/exodus/
  exodus_path: baby-bosh/concourse
  min_version: 2.7.6
  secrets_mount: /secret/
  secrets_path: baby/bosh/concourse
instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: worker
    properties:
      baggageclaim:
        driver: detect
      http_proxy_url: ""
      https_proxy_url: ""
      no_proxy:
      - localhost
      - 127.0.0.1
      runtime: containerd
      worker_gateway:
        worker_key:
          private_key: REDACTED
          public_key: REDACTED
    release: concourse
  name: worker
  networks:
  - name: concourse-ips
  stemcell: default
  update:
    max_in_flight: 1
    serial: true
  vm_type: concourse-worker
- azs:
  - z1
  instances: 1
  jobs:
  - name: postgres
    properties:
      databases:
        databases:
        - name: atc
        port: 5432
        roles:
        - name: atc
          password: REDACTED
    release: postgres
  - name: locker
    properties:
      locker:
        password: REDACTED
        ssl_cert: REDACTED
        ssl_key: REDACTED
        user: locker
    release: locker
  - name: web
    properties:
      add_local_users:
      - concourse:REDACTED
      bind_port: 80
      external_url: https://10.4.68.6
      main_team:
        auth:
          local:
            users:
            - concourse
      postgresql:
        database: atc
        role:
          name: atc
          password: REDACTED
      publicly_viewable: true
      tls:
        bind_port: 443
        cert:
          certificate: REDACTED
          private_key: REDACTED
      token_signing_key:
        private_key: REDACTED
        public_key: REDACTED
      worker_gateway:
        authorized_keys:
        - REDACTED
        host_key:
          private_key: REDACTED
          public_key: REDACTED
    release: concourse
  - name: bpm
    properties:
      bind_port: 80
    release: bpm
  name: concourse
  networks:
  - name: concourse-ips
    static_ips:
    - 10.4.68.6
  stemcell: default
  vm_type: small
kit:
  features:
  - small-footprint
  - self-signed-cert
  name: dev
  version: latest
meta:
  default:
    azs:
    - z1
    - z2
    - z3
    main_user: concourse
    no_proxy:
    - localhost
    - 127.0.0.1
  http_auth_password: REDACTED
  jobs:
    bpm:
      release: bpm
    haproxy:
      properties:
        ha_proxy:
          tcp:
          - backend_port: 80
            backend_servers:
            - 10.4.68.6
            name: web_http
            port: 80
          - backend_port: 443
            backend_servers:
            - 10.4.68.6
            name: web_https
            port: 443
      release: haproxy
    locker:
      properties:
        locker:
          password: REDACTED
          ssl_cert: REDACTED
          ssl_key: REDACTED
          user: locker
      release: locker
    postgres:
      properties:
        databases:
          databases:
          - name: atc
          port: 5432
          roles:
          - name: atc
            password: REDACTED
      release: postgres
    web:
      properties:
        add_local_users:
        - concourse:REDACTED
        bind_port: 80
        external_url: https://10.4.68.6
        main_team:
          auth:
            local:
              users:
              - concourse
        postgresql:
          database: atc
          role:
            name: atc
            password: REDACTED
        publicly_viewable: true
        tls:
          bind_port: 443
          cert:
            certificate: REDACTED
            private_key: REDACTED
        token_signing_key:
          private_key: REDACTED
          public_key: REDACTED
        worker_gateway:
          authorized_keys:
          - REDACTED
          host_key:
            private_key: REDACTED
            public_key: REDACTED
      release: concourse
    worker:
      properties:
        baggageclaim:
          driver: detect
        http_proxy_url: ""
        https_proxy_url: ""
        no_proxy:
        - localhost
        - 127.0.0.1
        runtime: containerd
        worker_gateway:
          worker_key:
            private_key: REDACTED
            public_key: REDACTED
      release: concourse
  vault: /secret/baby/bosh/concourse
name: baby-bosh-concourse
networks:
- name: default
  subnets:
  - azs:
    - z1
    cloud_properties:
      subnet: subnet-0dcf8272f03fead6d
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.69.1
    range: 10.4.69.0/24
    reserved:
    - 10.4.69.0-10.4.69.5
    static:
    - 10.4.69.6-10.4.69.16
  type: manual
- name: concourse-ips
  subnets:
  - azs:
    - z1
    cloud_properties:
      subnet: subnet-004e38051f36dae09
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.68.1
    range: 10.4.68.0/24
    reserved:
    - 10.4.68.0-10.4.68.5
    static:
    - 10.4.68.6-10.4.68.16
  type: manual
- name: cf-edge
  subnets:
  - azs:
    - z1
    cloud_properties:
      subnet: subnet-0a586efdf31f74d60
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.64.1
    range: 10.4.64.0/24
    reserved:
    - 10.4.64.0-10.4.64.5
    static:
    - 10.4.64.6-10.4.64.16
  type: manual
- name: cf-runtime
  subnets:
  - azs:
    - z1
    cloud_properties:
      subnet: subnet-017e62bca32e491ea
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.65.1
    range: 10.4.65.0/24
    reserved:
    - 10.4.65.0-10.4.65.5
    static:
    - 10.4.65.6-10.4.65.16
  type: manual
- name: cf-core
  subnets:
  - azs:
    - z1
    cloud_properties:
      subnet: subnet-06001ccd9bca8ac63
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.66.1
    range: 10.4.66.0/24
    reserved:
    - 10.4.66.0-10.4.66.5
    static:
    - 10.4.66.6-10.4.66.16
  type: manual
params:
  availability_zones:
  - z1
  concourse_disk_type: concourse
  concourse_network: concourse-ips
  concourse_vm_type: small
  external_db_host: baby-bosh-concourse-db.cmziohdu4x1g.us-west-2.rds.amazonaws.com
  external_domain: 10.4.68.6
  external_url: https://10.4.68.6
  num_web_nodes: 1
  stemcell_os: ubuntu-bionic
  stemcell_version: latest
  token_signing_key:
    private_key: REDACTED
    public_key: REDACTED
  volume_driver: detect
  worker_vm_type: concourse-worker
  workers: 1
releases:
- name: concourse
  sha1: 1e242ed38f73de72ba1bb48f85ea7fbf7eb634a1
  url: https://bosh.io/d/github.com/concourse/concourse-bosh-release?v=7.7.1
  version: 7.7.1
- name: slack-notification-resource
  sha1: a64c65d1f23ea089746e698f29dbe522dd716c1b
  url: https://bosh.io/d/github.com/cloudfoundry-community/slack-notification-resource-boshrelease?v=9
  version: 9
- name: postgres
  sha1: e44bbe8f8a7cdde1cda67b202e399a239d104db6
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=43
  version: 43
- name: locker
  sha1: ccfcc48d63555a3733c3594d9429a5c1875a9dd2
  url: https://github.com/cloudfoundry-community/locker-boshrelease/releases/download/v0.2.1/locker-0.2.1.tgz
  version: 0.2.1
- name: bpm
  sha1: 0d48aa01a65b947b97570234eb2401e821a8bd35
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.15
  version: 1.1.15
stemcells:
- alias: default
  os: ubuntu-bionic
  version: latest
update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 4
  serial: false
  update_watch_time: 1000-60000
vm_extensions:
- cloud_properties:
    ephemeral_disk:
      size: 102400
      type: gp3
  name: 100GB_ephemeral_disk
- cloud_properties:
    ephemeral_disk:
      size: 51200
      type: gp3
  name: 50GB_ephemeral_disk
- cloud_properties:
    elbs:
    - snw-dev-cf-elb
  name: cf-router-network-properties
- cloud_properties:
    elbs:
    - dev-cf-tcp-lb
  name: cf-tcp-router-network-properties
- name: diego-ssh-proxy-network-properties
vm_types:
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 32768
      type: gp3
    instance_type: t3.small
  name: api
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 16384
      type: gp3
    instance_type: t3.nano
  name: as-api
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 16384
      type: gp3
    instance_type: t3.nano
  name: as-broker
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 16384
      type: gp3
    instance_type: t3.nano
  name: as-collector
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 16384
      type: gp3
    instance_type: t3.nano
  name: as-engine
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 16384
      type: gp3
    instance_type: t3.nano
  name: as-operator
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 16384
      type: gp3
    instance_type: t3.nano
  name: as-scaler
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 16384
      type: gp3
    instance_type: t3.nano
  name: as-scheduler
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 8192
      type: gp3
    instance_type: t3.nano
  name: bbs
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 16384
      type: gp3
    instance_type: t3.nano
  name: blobstore
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 24576
      type: gp3
    instance_type: t3.medium
  name: bosh
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 8192
      type: gp3
    instance_type: t3.nano
  name: cc-worker
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 65536
      type: gp3
    instance_type: t3.nano
  name: compilation
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 65536
      type: gp3
    instance_type: t3.nano
  name: concourse-worker
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 16384
      type: gp3
    instance_type: t3.nano
  name: credhub
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 8192
      type: gp3
    instance_type: t3.nano
  name: default
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 262144
      type: gp3
    instance_type: t3.small
  name: diego-cell
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 32768
      type: gp3
    instance_type: t3.nano
  name: diego-api
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 32768
      type: gp3
    instance_type: t3.medium
  name: doppler
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 8192
      type: gp3
    instance_type: t3.small
  name: errand
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 8192
      type: gp3
    instance_type: t3.small
  name: haproxy
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 32768
      type: gp3
    instance_type: t3.small
  name: large
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 16384
      type: gp3
    instance_type: t3.small
  name: log-api
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 16384
      type: gp3
    instance_type: t3.micro
  name: medium
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 10240
      type: gp3
    instance_type: t3.nano
  name: minimal
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 8192
      type: gp3
    instance_type: t3.nano
  name: nats
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 32768
      type: gp3
    instance_type: t3.medium
  name: postgres
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 8192
      type: gp3
    instance_type: t3.small
  name: router
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 8192
      type: gp3
    instance_type: t3.small
  name: scheduler
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 8192
      type: gp3
    instance_type: t3.nano
  name: small
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 10240
      type: gp3
    instance_type: t3.nano
  name: small-cf
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 24576
      type: gp3
    instance_type: t3.nano
  name: small-highmem
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 8192
      type: gp3
    instance_type: t3.small
  name: syslogger
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 8192
      type: gp3
    instance_type: t3.nano
  name: tcp-router
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 81920
      type: gp3
    instance_type: t3.small
  name: thunder-dome
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 16384
      type: gp3
    instance_type: t3.small
  name: uaa
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 10240
      type: gp3
    instance_type: t3.medium
  name: blacksmith
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 10240
      type: gp3
    instance_type: t3.small
  name: blacksmith-redis-small
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 10240
      type: gp3
    instance_type: t3.medium
  name: blacksmith-redis-medium
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 10240
      type: gp3
    instance_type: t3.large
  name: blacksmith-redis-large
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 10240
      type: gp3
    instance_type: t3.small
  name: blacksmith-rabbitmq-medium
- cloud_properties:
    ephemeral_disk:
      encrypted: true
      size: 10240
      type: gp3
    instance_type: t3.medium
  name: blacksmith-rabbitmq-large