azs:
- cloud_properties:
    availability_zone: us-west-2a
  name: z1
- cloud_properties:
    availability_zone: us-west-2b
  name: z2
- cloud_properties:
    availability_zone: us-west-2c
  name: z3
compilation:
  az: z1
  network: default
  reuse_compilation_vms: true
  vm_type: large
  workers: 5
disk_types:
- cloud_properties:
    type: gp2
  disk_size: 3000
  name: default
- cloud_properties:
    type: gp2
  disk_size: 50000
  name: large
- cloud_properties:
    type: gp2
  disk_size: 50000
  name: bosh
- cloud_properties:
    type: gp3
  disk_size: 10240
  name: concourse
exodus:
  bosh: uswest2demo
  dated: 2022-07-21 15:17:57 +0000
  deployer: ubuntu
  features: workers
  host_env: uswest2demo-full
  is_director: false
  kit_is_dev: true
  kit_name: concourse
  kit_version: 4.1.3-rc.5
  mode: worker
  tags:
  - uswest2demo
  - dev
  use_create_env: false
  vault_base: /secret/uswest2demo/full/concourse
  version: 2.8.5
genesis:
  ci_mount: /secret/ci/
  env: uswest2demo
  exodus_mount: /secret/exodus/
  exodus_path: uswest2demo/concourse
  min_version: 2.7.6
  secrets_mount: /secret/
  secrets_path: uswest2demo/full/concourse
instance_groups:
- azs:
  - z1
  - z2
  - z3
  instances: 3
  jobs:
  - name: worker
    properties:
      baggageclaim:
        driver: detect
      http_proxy_url: ""
      https_proxy_url: ""
      no_proxy:
      - localhost
      - 127.0.0.1
      runtime: containerd
      tags:
      - uswest2demo
      - dev
      worker_gateway:
        host_public_key: REDACTED
        hosts:
        - REDACTED:REDACTED
        worker_key:
          private_key: REDACTED
          public_key: REDACTED
    release: concourse
  name: worker
  networks:
  - name: concourse
  stemcell: default
  update:
    max_in_flight: 3
    serial: true
  vm_type: concourse-worker
kit:
  features:
  - workers
  name: dev
  version: latest
meta:
  default:
    azs:
    - z1
    - z2
    - z3
    no_proxy:
    - localhost
    - 127.0.0.1
    tags:
    - uswest2demo
  http_auth_password: REDACTED
  jobs:
    bpm: null
    haproxy: null
    locker: null
    postgres: null
    web: null
    worker:
      properties:
        baggageclaim:
          driver: detect
        http_proxy_url: ""
        https_proxy_url: ""
        no_proxy:
        - localhost
        - 127.0.0.1
        runtime: containerd
        worker_gateway:
          worker_key:
            private_key: REDACTED
            public_key: REDACTED
      release: concourse
  tsa:
    host: REDACTED
    port: REDACTED
  vault: /secret/uswest2demo/full/concourse
name: uswest2demo-concourse
networks:
- name: default
  subnets:
  - azs:
    - z1
    cloud_properties:
      subnet: subnet-0f56fcba8b1ba95b3
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.1.1
    range: 10.4.1.0/24
    reserved:
    - 10.4.1.0-10.4.1.5
    static:
    - 10.4.1.6-10.4.1.16
  - azs:
    - z2
    cloud_properties:
      subnet: subnet-04066d0a30fd1c020
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.2.1
    range: 10.4.2.0/24
    reserved:
    - 10.4.2.0-10.4.2.5
    static:
    - 10.4.2.6-10.4.2.16
  - azs:
    - z3
    cloud_properties:
      subnet: subnet-0f2b10a0d103f3c83
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.3.1
    range: 10.4.3.0/24
    reserved:
    - 10.4.3.0-10.4.3.5
    static:
    - 10.4.3.6-10.4.3.16
  type: manual
- name: concourse
  subnets:
  - azs:
    - z1
    cloud_properties:
      subnet: subnet-0f56fcba8b1ba95b3
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.1.1
    range: 10.4.1.0/24
    reserved:
    - 10.4.1.0-10.4.1.99
    static:
    - 10.4.1.100-10.4.1.106
  - azs:
    - z2
    cloud_properties:
      subnet: subnet-04066d0a30fd1c020
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.2.1
    range: 10.4.2.0/24
    reserved:
    - 10.4.2.0-10.4.2.99
    static:
    - 10.4.2.100-10.4.2.106
  - azs:
    - z3
    cloud_properties:
      subnet: subnet-0f2b10a0d103f3c83
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.3.1
    range: 10.4.3.0/24
    reserved:
    - 10.4.3.0-10.4.3.99
    static:
    - 10.4.3.100-10.4.3.106
  type: manual
- name: concourse-full
  subnets:
  - azs:
    - z1
    cloud_properties:
      subnet: subnet-0f56fcba8b1ba95b3
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.1.1
    range: 10.4.1.0/24
    reserved:
    - 10.4.1.0-10.4.1.99
    static:
    - 10.4.1.150-10.4.1.156
  - azs:
    - z2
    cloud_properties:
      subnet: subnet-04066d0a30fd1c020
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.2.1
    range: 10.4.2.0/24
    reserved:
    - 10.4.2.0-10.4.2.99
    static:
    - 10.4.2.150-10.4.2.156
  - azs:
    - z3
    cloud_properties:
      subnet: subnet-0f2b10a0d103f3c83
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.3.1
    range: 10.4.3.0/24
    reserved:
    - 10.4.3.0-10.4.3.99
    static:
    - 10.4.3.150-10.4.3.156
  type: manual
- name: dev
  subnets:
  - azs:
    - z1
    cloud_properties:
      subnet: subnet-0ea631cc3ad19e04f
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.16.1
    range: 10.4.16.0/24
    reserved:
    - 10.4.16.0-10.4.16.3
    static:
    - 10.4.16.4-10.4.16.16
  - azs:
    - z2
    cloud_properties:
      subnet: subnet-09a05edb82702379b
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.17.1
    range: 10.4.17.0/24
    reserved:
    - 10.4.17.0-10.4.17.3
    static:
    - 10.4.17.4-10.4.17.16
  - azs:
    - z3
    cloud_properties:
      subnet: subnet-0dd034854c197dc41
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.18.1
    range: 10.4.18.0/24
    reserved:
    - 10.4.18.0-10.4.18.3
    static:
    - 10.4.18.4-10.4.18.16
  type: manual
- name: baby
  subnets:
  - azs:
    - z1
    cloud_properties:
      subnet: subnet-064b78e587e3b8bf5
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.63.1
    range: 10.4.63.0/24
    reserved:
    - 10.4.63.0-10.4.63.3
    static:
    - 10.4.63.4-10.4.63.16
  type: manual
params:
  concourse_disk_type: concourse
  concourse_network: concourse
  concourse_vm_type: small
  env: uswest2demo
  external_domain: concourse.codex.starkandwayne.com
  num_web_nodes: 1
  stemcell_os: ubuntu-bionic
  stemcell_version: latest
  tags:
  - uswest2demo
  - dev
  tsa_host_env: uswest2demo-full
  vault_prefix: uswest2demo/full/concourse
  volume_driver: detect
  worker_vm_type: concourse-worker
  workers: 3
releases:
- name: concourse
  sha1: 1e242ed38f73de72ba1bb48f85ea7fbf7eb634a1
  url: https://bosh.io/d/github.com/concourse/concourse-bosh-release?v=7.7.1
  version: 7.7.1
- name: slack-notification-resource
  sha1: a64c65d1f23ea089746e698f29dbe522dd716c1b
  url: https://bosh.io/d/github.com/cloudfoundry-community/slack-notification-resource-boshrelease?v=9
  version: 9
stemcells:
- alias: default
  os: ubuntu-bionic
  version: latest
update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 4
  serial: false
  update_watch_time: 1000-60000
vm_types:
- cloud_properties:
    ephemeral_disk:
      size: 3000
      type: gp2
    instance_type: t2.small
  name: default
- cloud_properties:
    ephemeral_disk:
      size: 30000
      type: gp2
    instance_type: t3.large
  name: large
- cloud_properties:
    ephemeral_disk:
      size: 25000
      type: gp2
    instance_type: t3.medium
  name: bosh
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp3
    instance_type: t3.large
  name: concourse
- cloud_properties:
    ephemeral_disk:
      size: 65536
      type: gp3
    instance_type: t3.medium
  name: concourse-worker