azs:
- cloud_properties:
    availability_zone: us-west-2a
  name: z1
- cloud_properties:
    availability_zone: us-west-2b
  name: z2
- cloud_properties:
    availability_zone: us-west-2c
  name: z3
compilation:
  az: z1
  network: default
  reuse_compilation_vms: true
  vm_type: large
  workers: 5
disk_types:
- cloud_properties:
    type: gp2
  disk_size: 3000
  name: default
- cloud_properties:
    type: gp2
  disk_size: 50000
  name: large
- cloud_properties:
    type: gp2
  disk_size: 50000
  name: bosh
- cloud_properties:
    type: gp3
  disk_size: 10240
  name: concourse
exodus:
  atc_ca_cert: REDACTED
  bosh: uswest2demo
  dated: 2022-07-14 14:59:44 +0000
  deployer: ubuntu
  external_url: https://concourse.codex.starkandwayne.com
  features: full,self-signed-cert,external-db,vault,vault-approle
  is_director: false
  kit_is_dev: true
  kit_name: concourse
  kit_version: 4.1.3-rc.5
  main_target: uswest2demo-full
  mode: full
  password: REDACTED
  self-signed: true
  tsa_host: 10.4.1.151
  tsa_host_public_key: REDACTED
  tsa_port: 2222
  tsa_worker_private_key: REDACTED
  tsa_worker_public_key: REDACTED
  use_create_env: false
  username: concourse
  vault_base: /secret/uswest2demo/full/concourse
  version: 2.8.5
genesis:
  bosh_env: uswest2demo
  ci_mount: /secret/ci/
  env: uswest2demo-full
  exodus_mount: /secret/exodus/
  exodus_path: uswest2demo-full/concourse
  min_version: 2.7.6
  secrets_mount: /secret/
  secrets_path: uswest2demo/full/concourse
instance_groups:
- azs:
  - z1
  - z2
  - z3
  instances: 3
  jobs:
  - name: worker
    properties:
      baggageclaim:
        driver: detect
      http_proxy_url: ""
      https_proxy_url: ""
      no_proxy:
      - localhost
      - 127.0.0.1
      runtime: containerd
      worker_gateway:
        worker_key:
          private_key: REDACTED
          public_key: REDACTED
    release: concourse
  name: worker
  networks:
  - name: concourse-full
  stemcell: default
  update:
    max_in_flight: 3
    serial: true
  vm_type: concourse-worker
- azs:
  - z1
  - z2
  - z3
  instances: 1
  jobs:
  - name: haproxy
    properties:
      ha_proxy:
        tcp:
        - backend_port: 80
          backend_servers:
          - 10.4.1.151
          name: web_http
          port: 80
        - backend_port: 443
          backend_servers:
          - 10.4.1.151
          name: web_https
          port: 443
    release: haproxy
  - name: bpm
    release: bpm
  name: haproxy
  networks:
  - name: concourse-full
    static_ips:
    - 10.4.1.150
  stemcell: default
  vm_type: concourse
- azs:
  - z1
  - z2
  - z3
  instances: 1
  jobs:
  - name: web
    properties:
      add_local_users:
      - concourse:REDACTED
      bind_port: 80
      external_url: https://concourse.codex.starkandwayne.com
      main_team:
        auth:
          local:
            users:
            - concourse
      postgresql:
        database: atc
        host: snw-dev-cf-db.cmziohdu4x1g.us-west-2.rds.amazonaws.com
        port: 5432
        role:
          name: cfdbadmin
          password: REDACTED
        sslmode: verify-ca
      publicly_viewable: true
      tls:
        bind_port: 443
        cert:
          certificate: REDACTED
          private_key: REDACTED
      token_signing_key:
        private_key: REDACTED
        public_key: REDACTED
      vault:
        auth:
          backend: approle
          backend_max_ttl: null
          client_token: REDACTED
          params:
            role_id: REDACTED
            secret_id: REDACTED
        path_prefix: /concourse
        tls:
          insecure_skip_verify: true
        url: https://10.4.1.7
      worker_gateway:
        authorized_keys:
        - REDACTED
        host_key:
          private_key: REDACTED
          public_key: REDACTED
    release: concourse
  - name: bpm
    release: bpm
  - name: locker
    properties:
      locker:
        password: REDACTED
        ssl_cert: REDACTED
        ssl_key: REDACTED
        user: locker
    release: locker
  name: web
  networks:
  - name: concourse-full
    static_ips:
    - 10.4.1.151
  stemcell: default
  vm_type: concourse
kit:
  features:
  - full
  - self-signed-cert
  - external-db
  - vault
  - vault-approle
  name: dev
  version: latest
meta:
  default:
    azs:
    - z1
    - z2
    - z3
    main_user: concourse
    no_proxy:
    - localhost
    - 127.0.0.1
  http_auth_password: REDACTED
  jobs:
    bpm:
      release: bpm
    haproxy:
      properties:
        ha_proxy:
          tcp:
          - backend_port: 80
            backend_servers:
            - 10.4.1.151
            name: web_http
            port: 80
          - backend_port: 443
            backend_servers:
            - 10.4.1.151
            name: web_https
            port: 443
      release: haproxy
    locker:
      properties:
        locker:
          password: REDACTED
          ssl_cert: REDACTED
          ssl_key: REDACTED
          user: locker
      release: locker
    web:
      properties:
        add_local_users:
        - concourse:REDACTED
        bind_port: 80
        external_url: https://concourse.codex.starkandwayne.com
        main_team:
          auth:
            local:
              users:
              - concourse
        postgresql:
          database: atc
          host: snw-dev-cf-db.cmziohdu4x1g.us-west-2.rds.amazonaws.com
          port: 5432
          role:
            name: cfdbadmin
            password: REDACTED
          sslmode: verify-ca
        publicly_viewable: true
        tls:
          bind_port: 443
          cert:
            certificate: REDACTED
            private_key: REDACTED
        token_signing_key:
          private_key: REDACTED
          public_key: REDACTED
        vault:
          auth:
            backend: approle
            backend_max_ttl: null
            params:
              role_id: REDACTED
              secret_id: REDACTED
          path_prefix: /concourse
          tls:
            insecure_skip_verify: true
          url: https://10.4.1.7
        worker_gateway:
          authorized_keys:
          - REDACTED
          host_key:
            private_key: REDACTED
            public_key: REDACTED
      release: concourse
    worker:
      properties:
        baggageclaim:
          driver: detect
        http_proxy_url: ""
        https_proxy_url: ""
        no_proxy:
        - localhost
        - 127.0.0.1
        runtime: containerd
        worker_gateway:
          worker_key:
            private_key: REDACTED
            public_key: REDACTED
      release: concourse
  vault: /secret/uswest2demo/full/concourse
name: uswest2demo-full-concourse
networks:
- name: default
  subnets:
  - azs:
    - z1
    cloud_properties:
      subnet: subnet-0f56fcba8b1ba95b3
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.1.1
    range: 10.4.1.0/24
    reserved:
    - 10.4.1.0-10.4.1.5
    static:
    - 10.4.1.6-10.4.1.16
  - azs:
    - z2
    cloud_properties:
      subnet: subnet-04066d0a30fd1c020
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.2.1
    range: 10.4.2.0/24
    reserved:
    - 10.4.2.0-10.4.2.5
    static:
    - 10.4.2.6-10.4.2.16
  - azs:
    - z3
    cloud_properties:
      subnet: subnet-0f2b10a0d103f3c83
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.3.1
    range: 10.4.3.0/24
    reserved:
    - 10.4.3.0-10.4.3.5
    static:
    - 10.4.3.6-10.4.3.16
  type: manual
- name: concourse
  subnets:
  - azs:
    - z1
    cloud_properties:
      subnet: subnet-0f56fcba8b1ba95b3
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.1.1
    range: 10.4.1.0/24
    reserved:
    - 10.4.1.0-10.4.1.99
    static:
    - 10.4.1.100-10.4.1.106
  - azs:
    - z2
    cloud_properties:
      subnet: subnet-04066d0a30fd1c020
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.2.1
    range: 10.4.2.0/24
    reserved:
    - 10.4.2.0-10.4.2.99
    static:
    - 10.4.2.100-10.4.2.106
  - azs:
    - z3
    cloud_properties:
      subnet: subnet-0f2b10a0d103f3c83
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.3.1
    range: 10.4.3.0/24
    reserved:
    - 10.4.3.0-10.4.3.99
    static:
    - 10.4.3.100-10.4.3.106
  type: manual
- name: concourse-full
  subnets:
  - azs:
    - z1
    cloud_properties:
      subnet: subnet-0f56fcba8b1ba95b3
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.1.1
    range: 10.4.1.0/24
    reserved:
    - 10.4.1.0-10.4.1.99
    static:
    - 10.4.1.150-10.4.1.156
  - azs:
    - z2
    cloud_properties:
      subnet: subnet-04066d0a30fd1c020
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.2.1
    range: 10.4.2.0/24
    reserved:
    - 10.4.2.0-10.4.2.99
    static:
    - 10.4.2.150-10.4.2.156
  - azs:
    - z3
    cloud_properties:
      subnet: subnet-0f2b10a0d103f3c83
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.3.1
    range: 10.4.3.0/24
    reserved:
    - 10.4.3.0-10.4.3.99
    static:
    - 10.4.3.150-10.4.3.156
  type: manual
- name: dev
  subnets:
  - azs:
    - z1
    cloud_properties:
      subnet: subnet-0ea631cc3ad19e04f
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.16.1
    range: 10.4.16.0/24
    reserved:
    - 10.4.16.0-10.4.16.3
    static:
    - 10.4.16.4-10.4.16.16
  - azs:
    - z2
    cloud_properties:
      subnet: subnet-09a05edb82702379b
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.17.1
    range: 10.4.17.0/24
    reserved:
    - 10.4.17.0-10.4.17.3
    static:
    - 10.4.17.4-10.4.17.16
  - azs:
    - z3
    cloud_properties:
      subnet: subnet-0dd034854c197dc41
    dns:
    - 1.1.1.1
    - 8.8.4.4
    gateway: 10.4.18.1
    range: 10.4.18.0/24
    reserved:
    - 10.4.18.0-10.4.18.3
    static:
    - 10.4.18.4-10.4.18.16
  type: manual
params:
  availability_zone:
  - z1
  - z2
  - z3
  concourse_disk_type: concourse
  concourse_network: concourse-full
  concourse_vm_type: concourse
  external_db_ca: |
    -----BEGIN CERTIFICATE-----
    MIIEBjCCAu6gAwIBAgIJAMc0ZzaSUK51MA0GCSqGSIb3DQEBCwUAMIGPMQswCQYD
    VQQGEwJVUzEQMA4GA1UEBwwHU2VhdHRsZTETMBEGA1UECAwKV2FzaGluZ3RvbjEi
    MCAGA1UECgwZQW1hem9uIFdlYiBTZXJ2aWNlcywgSW5jLjETMBEGA1UECwwKQW1h
    em9uIFJEUzEgMB4GA1UEAwwXQW1hem9uIFJEUyBSb290IDIwMTkgQ0EwHhcNMTkw
    ODIyMTcwODUwWhcNMjQwODIyMTcwODUwWjCBjzELMAkGA1UEBhMCVVMxEDAOBgNV
    BAcMB1NlYXR0bGUxEzARBgNVBAgMCldhc2hpbmd0b24xIjAgBgNVBAoMGUFtYXpv
    biBXZWIgU2VydmljZXMsIEluYy4xEzARBgNVBAsMCkFtYXpvbiBSRFMxIDAeBgNV
    BAMMF0FtYXpvbiBSRFMgUm9vdCAyMDE5IENBMIIBIjANBgkqhkiG9w0BAQEFAAOC
    AQ8AMIIBCgKCAQEArXnF/E6/Qh+ku3hQTSKPMhQQlCpoWvnIthzX6MK3p5a0eXKZ
    oWIjYcNNG6UwJjp4fUXl6glp53Jobn+tWNX88dNH2n8DVbppSwScVE2LpuL+94vY
    0EYE/XxN7svKea8YvlrqkUBKyxLxTjh+U/KrGOaHxz9v0l6ZNlDbuaZw3qIWdD/I
    6aNbGeRUVtpM6P+bWIoxVl/caQylQS6CEYUk+CpVyJSkopwJlzXT07tMoDL5WgX9
    O08KVgDNz9qP/IGtAcRduRcNioH3E9v981QO1zt/Gpb2f8NqAjUUCUZzOnij6mx9
    McZ+9cWX88CRzR0vQODWuZscgI08NvM69Fn2SQIDAQABo2MwYTAOBgNVHQ8BAf8E
    BAMCAQYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUc19g2LzLA5j0Kxc0LjZa
    pmD/vB8wHwYDVR0jBBgwFoAUc19g2LzLA5j0Kxc0LjZapmD/vB8wDQYJKoZIhvcN
    AQELBQADggEBAHAG7WTmyjzPRIM85rVj+fWHsLIvqpw6DObIjMWokpliCeMINZFV
    ynfgBKsf1ExwbvJNzYFXW6dihnguDG9VMPpi2up/ctQTN8tm9nDKOy08uNZoofMc
    NUZxKCEkVKZv+IL4oHoeayt8egtv3ujJM6V14AstMQ6SwvwvA93EP/Ug2e4WAXHu
    cbI1NAbUgVDqp+DRdfvZkgYKryjTWd/0+1fS8X1bBZVWzl7eirNVnHbSH2ZDpNuY
    0SBd8dj5F6ld3t58ydZbrTHze7JJOd8ijySAp4/kiu9UfZWuTPABzDa/DSdz9Dk/
    zPW4CXXvhLmE02TA9/HeCw3KEHIwicNuEfw=
    -----END CERTIFICATE-----
  external_db_host: snw-dev-cf-db.cmziohdu4x1g.us-west-2.rds.amazonaws.com
  external_db_name: atc
  external_db_port: 5432
  external_db_sslmode: verify-ca
  external_db_user: cfdbadmin
  external_domain: concourse.codex.starkandwayne.com
  external_url: https://concourse.codex.starkandwayne.com
  num_web_nodes: 1
  stemcell_os: ubuntu-bionic
  stemcell_version: latest
  token_signing_key:
    private_key: REDACTED
    public_key: REDACTED
  vault_approle_role_id: REDACTED
  vault_approle_secret_id: REDACTED
  vault_auth_backend: approle
  vault_insecure_skip_verify: true
  vault_token: REDACTED
  vault_url: https://10.4.1.7
  volume_driver: detect
  worker_count: 3
  worker_vm_type: concourse-worker
  workers: 3
releases:
- name: concourse
  sha1: 1e242ed38f73de72ba1bb48f85ea7fbf7eb634a1
  url: https://bosh.io/d/github.com/concourse/concourse-bosh-release?v=7.7.1
  version: 7.7.1
- name: slack-notification-resource
  sha1: a64c65d1f23ea089746e698f29dbe522dd716c1b
  url: https://bosh.io/d/github.com/cloudfoundry-community/slack-notification-resource-boshrelease?v=9
  version: 9
- name: locker
  sha1: ccfcc48d63555a3733c3594d9429a5c1875a9dd2
  url: https://github.com/cloudfoundry-community/locker-boshrelease/releases/download/v0.2.1/locker-0.2.1.tgz
  version: 0.2.1
- name: haproxy
  sha1: 3977888a5b0fdcccf8f30a64165dcc7b1cec67ca
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/haproxy-boshrelease?v=11.10.1
  version: 11.10.1
- name: bpm
  sha1: 0d48aa01a65b947b97570234eb2401e821a8bd35
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.15
  version: 1.1.15
stemcells:
- alias: default
  os: ubuntu-bionic
  version: latest
update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 4
  serial: false
  update_watch_time: 1000-60000
vm_types:
- cloud_properties:
    ephemeral_disk:
      size: 3000
      type: gp2
    instance_type: t2.small
  name: default
- cloud_properties:
    ephemeral_disk:
      size: 30000
      type: gp2
    instance_type: t3.large
  name: large
- cloud_properties:
    ephemeral_disk:
      size: 25000
      type: gp2
    instance_type: t3.medium
  name: bosh
- cloud_properties:
    ephemeral_disk:
      size: 10240
      type: gp3
    instance_type: t3.large
  name: concourse
- cloud_properties:
    ephemeral_disk:
      size: 65536
      type: gp3
    instance_type: t3.medium
  name: concourse-worker