pipeline:
  name: concourse-platform-pipeline
  git:
    owner: starkandwayne
    # change to concourse deploy once available
    repo:  demo-cf-deployments
    branch: master
    private_key: (( vault "concourse/main/github:private_key" ))

  vault:
    url:    https://10.4.1.7
    verify: yes
    role: (( vault "concourse/genesis/vault:role_id" ))
    secret: (( vault "concourse/genesis/vault:secret_id" ))
  
  slack:
    channel: '#botspam'
    webhook: (( vault "concourse/genesis/slack:webhook" ))

  boshes:
    # just to mimic the flow for now
    # it is okay if dev fails since we dont want it anyway
    dev:
      alias:    dev
      url:      https://10.4.1.4:25555
      ca_cert:  (( vault "secret/uswest2demo/bosh/ssl/ca:certificate" ))
      username: admin
      password: (( vault "secret/uswest2demo/bosh/users/admin:password" ))
    uswest2demo-full:
      alias:    uswest2demo
      url:      https://10.4.1.4:25555
      ca_cert:  (( vault "secret/uswest2demo/bosh/ssl/ca:certificate" ))
      username: admin
      password: (( vault "secret/uswest2demo/bosh/users/admin:password" ))
    
  layouts:
    default: |+
      auto *uswest2demo-full
      uswest2demo-full -> dev

  groups:
    default:
    - uswest2demo-full
    - dev
